"use client";
import { useState } from "react";
import Image from "next/image";
import ThemeToggle from "../ThemeToggle";
export default function AuthForm({onSuccess,connectionError}:{onSuccess:()=>Promise<void>;connectionError:string}){
 const [register,setRegister]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const values=new FormData(event.currentTarget);try{const response=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:register?"register":"login",email:values.get("email"),password:values.get("password"),...(register?{name:values.get("name")}: {})})});const result=await response.json();if(!response.ok)throw Error(result.error);await onSuccess();}catch(e){setError(e instanceof Error?e.message:"Não foi possível entrar.");}finally{setBusy(false);}}
 return <main className="auth-screen"><div className="auth-top"><span>MENTORIA COELHO</span><ThemeToggle/></div><section className="auth-card"><Image src="/brand/coelho.png" width={68} height={80} alt="Mentoria Coelho"/><p className="eyebrow">SEU PRÓXIMO PASSO COMEÇA AQUI</p><h1>{register?"Crie seu espaço.":"Bom ter você aqui."}</h1><p>Organize sua rotina e acompanhe cada conquista.</p><form onSubmit={submit} className="quick-add-form">{register&&<label>Seu nome<input name="name" required minLength={2} maxLength={80} autoComplete="name"/></label>}<label>E-mail<input name="email" type="email" required maxLength={254} autoComplete="email"/></label><label>Senha<input name="password" type="password" required minLength={12} maxLength={128} autoComplete={register?"new-password":"current-password"}/></label><p className="field-hint">Use pelo menos 12 caracteres.</p>{(error||connectionError)&&<p role="alert">{error||connectionError}</p>}<button type="submit" className="primary-button" disabled={busy}>{busy?"Aguarde…":register?"Criar conta":"Entrar"}</button><button type="button" disabled={busy} className="panel-link" onClick={()=>{setRegister(!register);setError("");}}>{register?"Já tenho uma conta":"Criar minha conta"}</button></form></section></main>;
}
