import { chromium } from 'playwright';
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage();
const result={};
await page.goto('http://localhost:3000/rotina');
await page.getByRole('button',{name:'Concluir Dormir antes das 23h',exact:true}).click();
result.habitChanged=await page.getByRole('button',{name:'Desmarcar Dormir antes das 23h',exact:true}).count()===1;
await page.reload();
result.habitLostAfterReload=await page.getByRole('button',{name:'Concluir Dormir antes das 23h',exact:true}).count()===1;
await page.goto('http://localhost:3000/perfil');
const before=await page.locator('.evolution-chart').getAttribute('aria-label');
const metrics=await page.locator('.performance-metrics').innerText();
await page.getByRole('button',{name:'7 dias',exact:true}).click();
result.metricsChange=metrics!==await page.locator('.performance-metrics').innerText();
result.chartUnchanged=before===await page.locator('.evolution-chart').getAttribute('aria-label');
await page.goto('http://localhost:3000');
await page.locator('.lesson-banner').click();
await page.waitForURL('**/rotina');
result.lessonDestination=new URL(page.url()).pathname;
console.log(JSON.stringify(result));
await browser.close();
