import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import {mkdirSync,writeFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
const base='http://localhost:3103';const out='test-results/interface-audit';mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const page=await context.newPage();const result={screens:[],violations:[],touch:[],findings:{},errors:[]};page.on('pageerror',e=>result.errors.push(e.message));
async function api(payload){const r=await context.request.post(base+'/api/study',{headers:{Origin:base},data:payload});if(!r.ok())throw Error(await r.text());return r.json();}
try{
 await page.goto(base);await page.locator('.auth-card').waitFor();await page.screenshot({path:out+'/login-desktop.png'});await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/login-mobile.png',fullPage:true});
 await context.request.post(base+'/api/auth',{headers:{Origin:base},data:{action:'register',name:'Aluno da Mentoria',email:`interface-${Date.now()}@example.test`,password:'Auditoria-Segura-2026!'}});
 const state=await (await context.request.get(base+'/api/study')).json();const today=state.today;const day=(n)=>{const d=new Date(today+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
 await page.goto(base);await page.locator('.app-shell').waitFor();await page.screenshot({path:out+'/empty-mobile.png',fullPage:true});
 const specs=[['Leitura e revisão de interpretação de texto','habit','count',20,'páginas',-7,'08:00','Todos os dias'],['Revisar os erros do simulado de Matemática','task','check',1,'',0,'14:00','Todos os dias'],['Enviar redação para correção do mentor','task','check',1,'',-2,'16:00','Todos os dias'],['Estudar Biologia: genética e suas aplicações','habit','count',30,'questões',-7,'10:00','Todos os dias'],['Revisar conteúdos apenas no fim de semana','habit','check',1,'',-7,'09:00','Fins de semana'],['Simulado completo com revisão dos conteúdos e planejamento da próxima semana','task','check',1,'',2,'08:00','Todos os dias']];
 const items=[];for(const [title,kind,measure,target,unit,offset,time,frequency] of specs){const item={id:randomUUID(),title,kind,measure,target,unit,date:day(offset),time,frequency,notes:'Organizar os materiais, fazer anotações e revisar os pontos de dificuldade.',priority:'Alta',value:0,done:false};await api({action:'save-item',item});items.push(item);}
 await api({action:'record',id:items[0].id,date:today,value:8,done:false,version:0});await api({action:'record',id:items[0].id,date:day(-1),value:20,done:true,version:0});await api({action:'save-plan',date:today,version:0,prioridades:'Revisar Matemática e finalizar a redação.',horarios:'08h às 10h: revisão. 14h às 16h: exercícios.',observacoes:'Separar dúvidas para a próxima mentoria.'});
 for(const theme of ['dark','light']){await page.evaluate(t=>localStorage.setItem('aristo-theme',t),theme);for(const width of [320,390,768,1024,1100,1440,1920]){await page.setViewportSize({width,height:900});for(const route of ['/','/rotina','/planos','/calendario','/perfil']){await page.goto(base+route);await page.locator('.app-shell').waitFor();const metrics=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,height:document.documentElement.scrollHeight,title:getComputedStyle(document.querySelector('main h1')).fontSize,nav:[...document.querySelectorAll('nav')].filter(e=>e.getBoundingClientRect().width>0).map(e=>({label:e.getAttribute('aria-label'),y:e.getBoundingClientRect().y,h:e.getBoundingClientRect().height}))}));result.screens.push({theme,width,route,...metrics});if([390,1440].includes(width)){await page.screenshot({path:out+`/${theme}-${width}-${route==='/'?'home':route.slice(1)}.png`,fullPage:true});const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();result.violations.push(...axe.violations.map(v=>({theme,width,route,id:v.id,targets:v.nodes.map(n=>n.target)})));}if(width===390){const small=await page.locator('.app-shell button,.app-shell a,.app-shell input').evaluateAll(els=>els.filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0&&!e.classList.contains('skip-link')&&(r.width<44||r.height<44)}).map(e=>({text:e.getAttribute('aria-label')||e.textContent.trim(),w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));if(small.length)result.touch.push({theme,route,small});}}}}
 await page.setViewportSize({width:390,height:844});await page.goto(base+'/planos');await page.getByLabel('Prioridades do dia',{exact:true}).fill('RASCUNHO NÃO SALVO');await page.getByLabel('Dia do planejamento').fill(day(1));await page.getByLabel('Dia do planejamento').fill(today);result.findings.unsavedPlanAfterDateSwitch=await page.getByLabel('Prioridades do dia',{exact:true}).inputValue();
 await page.goto(base+'/rotina');await page.getByRole('button',{name:'Editar '+items[0].title,exact:true}).click();await page.screenshot({path:out+'/edit-mobile.png',fullPage:true});await page.keyboard.press('Escape');result.findings.focusAfterEditEscape=await page.evaluate(()=>({tag:document.activeElement.tagName,label:document.activeElement.getAttribute('aria-label')}));
 await page.getByRole('button',{name:'Adicionar hábito ou tarefa'}).click();await page.locator('.quick-add-options button').first().click();await page.getByLabel('Nome',{exact:true}).fill('Rascunho do hábito');await page.keyboard.press('Escape');await page.getByRole('button',{name:'Adicionar hábito ou tarefa'}).click();await page.locator('.quick-add-options button').first().click();result.findings.draftAfterClose=await page.getByLabel('Nome',{exact:true}).inputValue();await page.setViewportSize({width:390,height:500});await page.getByLabel('Observações',{exact:false}).focus();await page.screenshot({path:out+'/short-viewport-form.png'});const modalAxe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();result.violations.push(...modalAxe.violations.map(v=>({route:'modal',id:v.id,targets:v.nodes.map(n=>n.target)})));await page.keyboard.press('Escape');
 await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/rotina');await page.getByRole('button',{name:'Todos os itens',exact:true}).click();await page.getByRole('button',{name:'Marcar como concluído',exact:true}).last().click({timeout:1000}).catch(()=>{});
 result.findings.unscheduledToday=await page.locator('.personal-items [role=alert]').allTextContents();
 // Directly reproduce ambiguity in a past calendar when a task was completed later.
 await api({action:'record',id:items[2].id,date:today,value:0,done:true,version:0});await page.goto(base+'/calendario');await page.getByLabel('Data da agenda').fill(day(-2));result.findings.pastTaskLabel=await page.locator('.personal-item').filter({hasText:items[2].title}).innerText();
 await page.goto(base);await page.getByRole('button',{name:'Recolher menu lateral'}).click();result.findings.collapsedNames=await page.locator('.desktop-nav a').evaluateAll(els=>els.map(e=>({title:e.title,text:e.textContent,aria:e.getAttribute('aria-label')})));
 writeFileSync(out+'/report.json',JSON.stringify(result,null,2));console.log(JSON.stringify({viewports:result.screens.length,overflow:result.screens.filter(s=>s.overflow),violations:result.violations,touch:result.touch,findings:result.findings,errors:result.errors},null,2));
}finally{await browser.close();}
